export default function arrayOfObjectsToCSV(arr) {
  const csvString = [
    [
      "Name",
      "Email",
      "Username",
      "Company",
      "Location",
      "New York?",
      "Bio",
      "Github URL",
      "User Bio Match",
      "Num. Pull Req. Repos w/ >100 stars",
      "Num. Pull Req. Repos w/ README Match",
      "Contributions",
      "Ten Star Repos",
      "User README Match",
      "Company is also Org.",
      "Github Followers",
      "Twitter Followers",
      "Num. User Orgs w/ Bio Match",
      "Num. User Orgs w/ >100 stars",
      "Num. User Orgs w/ README match",
    ],
    ...arr.map((e) => [
      e.name.replaceAll(",", ""),
      e.email,
      e.username,
      e.company.replaceAll(",", ";"),
      e.location.replaceAll(",", ""),
      e.bio.replaceAll("\n", "").replaceAll(",", ";"),
      e.githubUrl,
      e.bioMatchesKeywords,
      e.numPullRequestReposWithHundredStars,
      e.numPullRequestReposWithReadmeKeywordMatch,
      e.contributionCount,
      e.tenStarRepoCount,
      e.isUserReadmeKeywordMatch,
      e.userCompanyIsOrg,
      e.githubFollowers,
      e.twitterFollowers,
      e.numOrgBioKeywordMatch,
      e.numOrgReposWithHundredStars,
      e.numOrgReposReadmeKeywordMatch,
    ]),
  ]
    .map((item) => item.join(","))
    .join("\n");
  return csvString;
}
